import Head from 'next/head'
import Image from 'next/image'
import classes from '../styles/Home.module.scss'
import Topbar from '../components/topbar/Topbar'
import Intro from '../components/intro/Intro'
import Portfolio from '../components/portfolio/Portfolio'
import Works from '../components/works/Works'
import Testimonials from '../components/testimonials/Testimonials'
import Contact from '../components/contact/Contact'
import { useState } from "react";

export default function Home() {
  const [topbarActive, setTopbarActive] = useState(false)

  const toolbarToggleHandler = () => {
    console.log('suka');
    topbarActive === false ? setTopbarActive(true) : setTopbarActive(false)
  }
  return (
    <div className={classes.container}>
      <Head>
        <title>Rostyslav Kanibolotskyi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={classes.app}>
        <Topbar toolbarToggle={toolbarToggleHandler} active={topbarActive}/>
        <div className={classes.sections}>
          <Intro/>
          <Portfolio/>
          <Works/>
          <Testimonials/>
          <Contact/>
        </div>
      </div>
    </div>
  )
}
