import Head from 'next/head'
import Image from 'next/image'
import classes from '../styles/Home.module.scss'
import Topbar from '../components/topbar/Topbar'
import Intro from '../components/intro/Intro'
import Portfolio from '../components/portfolio/Portfolio'
import Works from '../components/works/Works'
import Testimonials from '../components/testimonials/Testimonials'
import Contact from '../components/contact/Contact'
import { useState } from "react";
import Menu from '../components/menu/Menu'

export default function Home() {
  const [topbarActive, setTopbarActive] = useState(false)

  const toolbarToggleHandler = () => {
    topbarActive === false ? setTopbarActive(true) : setTopbarActive(false)
  }

  const deactivateTopbarHandler = () => {
    setTopbarActive(false)
  }
  return (
    <div className={classes.container}>
      <Head>
        <title>Rostyslav Kanibolotskyi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={classes.app}>
        <Topbar toolbarToggle={toolbarToggleHandler} active={topbarActive}/>
        <Menu active={topbarActive} deactivateTopbar={toolbarToggleHandler}/>
        <div className={classes.sections} onClick={deactivateTopbarHandler}>
          <Intro/>
          <Portfolio/>
          <Works/>
          <Contact/>
        </div>
      </div>
    </div>
  )
}

// export async function getServerSideProps() {
//   const [operationsRes, incidentsRes] = await Promise.all([
//     fetch(`${process.env.APP_DOMAIN}/api/${apiRoute}`),
//     fetch(`${process.env.APP_DOMAIN}/api/${apiRoute2}`)
//   ]);
//   const [operations, incidents] = await Promise.all([
//     operationsRes.json(),
//     incidentsRes.json()
//   ]);
//   return { props: { operations, incidents } };
// }
